name: Update Exchange Rate

on:
  workflow_dispatch:
  schedule:
    # 每天 UTC 00:00 (台灣時間早上 8:00) 執行
    - cron: '0 0 * * *' 

jobs:
  update-rate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and process exchange rate
        run: |
          # 使用一個穩定且公開的匯率 API (此處選擇 Freecurrencyapi)
          # Freecurrencyapi 提供了一個不需要 Key 的 endpoint，但可能有請求限制
          API_URL="https://api.freecurrencyapi.com/v1/latest?apikey=fca_live_example&base_currency=TWD&currencies=JPY"
          
          echo "Fetching rate from API..."
          
          # 使用 curl 抓取數據
          RATE_DATA=$(curl -s "$API_URL")

          # 檢查 curl 是否成功
          if [ $? -ne 0 ]; then
            echo "::error::Curl failed to fetch data."
            exit 1
          fi

          # 使用 jq (JSON 處理工具) 提取 JPY 匯率值
          JPY_RATE=$(echo "$RATE_DATA" | jq -r '.data.JPY')
          
          # 檢查是否成功提取匯率
          if [ -z "$JPY_RATE" ] || [ "$JPY_RATE" == "null" ]; then
            echo "::error::Failed to extract JPY rate. API response might be invalid."
            echo "Response: $RATE_DATA"
            exit 1
          fi

          echo "TWD/JPY Rate: $JPY_RATE"
          
          # 創建新的 JSON 文件
          cat <<EOF > latest_rate.json
{
  "last_updated": "$(date -u +'%Y-%m-%d %H:%M:%S UTC')",
  "twd_to_jpy": $JPY_RATE
}
EOF
          echo "Created latest_rate.json"

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 只推送變更後的 JSON 檔案
          file_pattern: latest_rate.json
          commit_message: "自動更新匯率：TWD/JPY"
          # 這個 token 應該在 Actions 中自動可用
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions <actions@github.com>'
